MODEL:
  TYPE: pool
  NAME: pool_m48_patch4_224
  DROP_PATH_RATE: 0.5
  POOL:
    LAYERS: [8, 8, 24, 8]
    EMBED_DIMS: [96, 192, 384, 768]
    MLP_RATIOS: [ 4, 4, 4, 4]
    DOWNSAMPLES: [ True, True,True, True]
