MODEL:
  TYPE: wavemlp
  NAME: wavemlp_m_224
  DROP_PATH_RATE: 0.5
  WAVEMLP:
    LAYERS: [6, 6, 18, 6]
    EMBED_DIMS: [96, 192, 384, 768]
    MLP_RATIOS: [ 4, 4, 4, 4]
    DOWNSAMPLES: [ True, True,True, True]
